---
- name: Ensure required packages are installed
  apt:
    name:
      - debootstrap
      - squashfs-tools
      - xorriso
      - grub-pc-bin
      - grub-efi-amd64-bin
      - isolinux
      - syslinux-utils
      - systemd-container
    state: present
    update_cache: true

- name: Create build directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{ playbook_dir }/build"
    - "{ playbook_dir }/build/chroot"
    - "{ playbook_dir }/build/image"

- name: Bootstrap base system
  command: >
    debootstrap --arch={{ ARCH }}
    {{ DISTRIBUTION }}
    { playbook_dir }/build/chroot
    {{ UBUNTU_MIRROR }}
  args:
    creates: "{ playbook_dir }/build/chroot/bin/bash"

- name: Stat all build directories
  stat:
    path: "{{ item }}"
  loop:
    - "{{ playbook_dir }}/build"
    - "{{ playbook_dir }}/build/chroot"
    - "{{ playbook_dir }}/build/image"
  register: build_dirs_stat

- name: Print stat result
  debug:
    var: build_dirs_stat
