---
- name: Ensure required packages are installed
  apt:
    name:
      - debootstrap
      - squashfs-tools
      - xorriso
      - grub-pc-bin
      - grub-efi-amd64-bin
      - isolinux
      - syslinux-utils
      - systemd-container
    state: present
    update_cache: true

- name: Create build directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ BUILD_BASE_PATH }}/build"
    - "{{ CHROOT_DIR }}"
    - "{{ IMAGE_DIR }}"

- name: Bootstrap base system
  command: >
    debootstrap --arch={{ ARCH }}
    {{ DISTRIBUTION }}
    {{ CHROOT_DIR }}
    {{ UBUNTU_MIRROR }}
  args:
    creates: "{{ CHROOT_DIR }}/bin/bash"

- name: Stat all build directories
  stat:
    path: "{{ item }}"
  loop:
    - "{{ BUILD_DIR }}"
    - "{{ CHROOT_DIR }}"
    - "{{ IMAGE_DIR }}"
  register: build_dirs_stat

- name: Print stat result
  debug:
    var: build_dirs_stat
 