# -------------------------------------------------------------
# Step 0: Prepare image directory structure and cleanup
# -------------------------------------------------------------

- name: Ensure previous image directory is removed (clean build)
  file:
    path: "{{ lookup('env','PWD') }}/build/image"
    state: absent

- name: Recreate image directory structure (casper, isolinux, install)
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ lookup('env','PWD') }}/build/image/casper"
    - "{{ lookup('env','PWD') }}/build/image/isolinux"
    - "{{ lookup('env','PWD') }}/build/image/install"

# -------------------------------------------------------------
# Step 1: Locate kernel and initrd inside chroot/boot
# -------------------------------------------------------------

- name: Find vmlinuz-* kernel image in chroot/boot
  find:
    paths: "{{ chroot_path }}/boot"
    patterns: "vmlinuz-*"
    file_type: file
  register: kernel_files
  vars:
    chroot_path: "{{ lookup('env','PWD') }}/build/chroot"

- name: Find initrd.img-* initramfs image in chroot/boot
  find:
    paths: "{{ chroot_path }}/boot"
    patterns: "initrd.img-*"
    file_type: file
  register: initrd_files
  vars:
    chroot_path: "{{ lookup('env','PWD') }}/build/chroot"

# -------------------------------------------------------------
# Step 2: Copy kernel and initrd files into image/casper/
# -------------------------------------------------------------

- name: Copy kernel and initrd to image/casper directory
  copy:
    remote_src: true
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "{{ kernel_files.files[0].path }}", dest: "{{ image_path }}/casper/vmlinuz" }
    - { src: "{{ initrd_files.files[0].path }}", dest: "{{ image_path }}/casper/initrd" }
  vars:
    image_path: "{{ lookup('env','PWD') }}/build/image"

# -------------------------------------------------------------
# Step 3: Create a compressed squashfs image of the chroot
# -------------------------------------------------------------

- name: Create squashfs from chroot excluding /boot directory
  command: >
    mksquashfs {{ chroot_path }}
    {{ image_path }}/casper/filesystem.squashfs
    -e boot
  args:
    creates: "{{ image_path }}/casper/filesystem.squashfs"
  vars:
    chroot_path: "{{ lookup('env','PWD') }}/build/chroot"
    image_path: "{{ lookup('env','PWD') }}/build/image"
