#!/bin/sh

lb config \
  --distribution noble \
  --binary-images iso-hybrid \
  --debian-installer live \
  --archive-areas "main restricted universe multiverse" \
  --mirror-bootstrap http://archive.ubuntu.com/ubuntu/ \
  --mirror-binary http://archive.ubuntu.com/ubuntu/ \
  --mode ubuntu

