- name: Create user 'ubuntu' if it doesn't exist (inside chroot)
  command: chroot {{ CHROOT_DIR }} bash -c "id ubuntu || (useradd -m -s /bin/bash ubuntu && echo 'ubuntu:ubuntu' | chpasswd)"
  become: true

- name: Add 'ubuntu' user to groups (sudo, adm, netdev, audio, video)
  command: chroot {{ CHROOT_DIR }} adduser ubuntu {{ item }}
  loop:
    - sudo
    - adm
    - netdev
    - audio
    - video
  become: true

- name: Create /run/user/1000 and set permissions
  file:
    path: "{{ CHROOT_DIR }}/run/user/1000"
    state: directory
    owner: 1000
    group: 1000
    mode: '0700'

- name: Append XDG_RUNTIME_DIR to .profile of ubuntu user
  lineinfile:
    path: "{{ CHROOT_DIR }}/home/ubuntu/.profile"
    line: "export XDG_RUNTIME_DIR=/run/user/1000"
    create: yes
    owner: 1000
    group: 1000
    mode: '0644'

- name: Ensure LightDM autologin config dir exists
  file:
    path: "{{ CHROOT_DIR }}/etc/lightdm/lightdm.conf.d"
    state: directory
    mode: '0755'

- name: Set default display manager to LightDM
  copy:
    content: "/usr/sbin/lightdm\n"
    dest: "{{ CHROOT_DIR }}/etc/X11/default-display-manager"

- name: Configure LightDM autologin (basic)
  copy:
    dest: "{{ CHROOT_DIR }}/etc/lightdm/lightdm.conf.d/50-autologin.conf"
    content: |
      [Seat:*]
      autologin-user=ubuntu
      autologin-session=xfce

- name: Configure LightDM autologin (cloudify custom)
  copy:
    dest: "{{ CHROOT_DIR }}/etc/lightdm/lightdm.conf.d/50-cloudify-autologin.conf"
    content: |
      [Seat:*]
      autologin-user=ubuntu
      autologin-user-timeout=0

- name: Configure NetworkManager to manage interfaces
  copy:
    dest: "{{ CHROOT_DIR }}/etc/NetworkManager/NetworkManager.conf"
    content: |
      [main]
      plugins=ifupdown,keyfile

      [ifupdown]
      managed=true
