- name: Remove default XFCE panels
  file:
    path: "{{ chroot_dir }}/home/ubuntu/.config/xfce4/panel"
    state: absent

- name: Ensure autostart folder exists
  file:
    path: "{{ chroot_dir }}/home/ubuntu/.config/autostart"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0755"

- name: Ensure Plank is the only autostart entry
  copy:
    dest: "{{ chroot_dir }}/home/ubuntu/.config/autostart/plank.desktop"
    content: |
      [Desktop Entry]
      Type=Application
      Exec=plank
      Hidden=false
      X-GNOME-Autostart-enabled=true
      Name=Plank
    owner: ubuntu
    group: ubuntu
    mode: "0644"

- name: Regenerate locale
  command: chroot {{ chroot_dir }} locale-gen

- name: Set default locale to en_US.UTF-8
  command: chroot {{ chroot_dir }} update-locale LANG=en_US.UTF-8

- name: Autoremove unneeded packages
  command: chroot {{ chroot_dir }} apt-get autoremove -y

- name: Clean APT cache
  command: chroot {{ chroot_dir }} apt-get clean

- name: Remove temporary files
  file:
    path: "{{ chroot_dir }}/tmp"
    state: absent
