---
- name: Ensure /proc, /sys, /dev, /run are mounted in chroot
  mount:
    path: "{{ chroot_path }}/{{ item.mount }}"
    src: "{{ item.src }}"
    fstype: bind
    opts: bind
    state: mounted
  loop:
    - { mount: "proc", src: "/proc" }
    - { mount: "sys",  src: "/sys" }
    - { mount: "dev",  src: "/dev" }
    - { mount: "run",  src: "/run" }
  vars:
    chroot_path: "{ playbook_dir }/build/chroot"

- name: Show CHROOT_DIR and current working directory
  debug:
    msg: >
      CHROOT_DIR is: {{ CHROOT_DIR }},
      PWD is: {{ lookup('env', 'PWD') }},
      CHROOT_Script  is : {{ lookup('env', 'PWD') }}/cloudify-os-main/chroot_scripts/,

- name: Debug - Verify chroot_dir existence and permissions
  ansible.builtin.stat:
    path: "{{ CHROOT_DIR }}"
  register: chroot_dir_stat
  become: true

- name: Debug - Show chroot_dir details
  debug:
    msg: "Chroot directory: {{ chroot_dir_stat }}"

- name: Run base system setup
  include_tasks: prepare_base.yml
  vars:
    chroot_dir: "{{ lookup('env', 'PWD') }}/build/chroot"

- name: Install locale, keyboard, and essential packages
  include_tasks: install_packages.yml
  vars:
    chroot_dir: "{{ lookup('env', 'PWD') }}/build/chroot"

- name: Configure User & LightDM
  include_tasks: configure_user_and_lightdm.yml
  vars:
    chroot_dir: "{{ lookup('env', 'PWD') }}/build/chroot"

- name: Optimize system and configure services
  include_tasks: optimize_and_services.yml
  vars:
    chroot_dir: "{{ lookup('env', 'PWD') }}/build/chroot"

- name: Apply XFCE WhiteSur theme and session settings
  include_tasks: xfce_theme_setup.yml
  vars:
    chroot_dir: "{{ lookup('env', 'PWD') }}/build/chroot"

#- name: Perform final XFCE cleanup and system tuning
#  include_tasks: final_cleanup.yml
#  vars:
#    chroot_dir: "{{ lookup('env', 'PWD') }}/build/chroot"


- name: Unmount virtual filesystems from chroot
  shell: "umount -lf {{ chroot_path }}/{{ item }}"
  loop:
    - proc
    - sys
    - dev
    - run
  ignore_errors: true
  vars:
    chroot_path: "{ playbook_dir }/build/chroot"
