- name: Optimize initramfs settings for faster boot (MODULES=most, COMPRESS=zstd)
  lineinfile:
    path: "{{ CHROOT_DIR }}/etc/initramfs-tools/initramfs.conf"
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
    create: yes
  loop:
    - { key: 'MODULES', value: 'most' }
    - { key: 'COMPRESS', value: 'zstd' }

- name: Update initramfs inside chroot
  command: chroot {{ CHROOT_DIR }} update-initramfs -u
  become: true

- name: Disable unneeded services inside chroot
  command: chroot {{ CHROOT_DIR }} systemctl disable {{ item }}
  loop:
    - bluetooth
    - avahi-daemon
    - ModemManager
    - cups
    - apport
  ignore_errors: yes
  become: true

- name: Mask sleep-related targets
  command: chroot {{ CHROOT_DIR }} systemctl mask {{ item }}
  loop:
    - sleep.target
    - suspend.target
    - hibernate.target
    - hybrid-sleep.target
  ignore_errors: yes
  become: true

- name: Enable LightDM and NetworkManager
  command: chroot {{ CHROOT_DIR }} systemctl enable {{ item }}
  loop:
    - lightdm
    - NetworkManager
  become: true

- name: Set graphical target as default (GUI login)
  command: chroot {{ CHROOT_DIR }} systemctl set-default graphical.target
  become: true
