
- name: Fix ownership of ubuntu user config files
  file:
    path: "{{ chroot_dir }}/home/ubuntu/.config"
    owner: 1000
    group: 1000
    recurse: yes

- name: Copy default wallpaper into chroot for user-level usage
  copy:
    src: "{{ playbook_dir }}/cloudify-os-main/cloudify-wallpaper.png"
    dest: "{{ chroot_dir }}/usr/share/backgrounds/xfce/cloudify-wallpaper.png"
  become: true

# ==== Theme =====
- name: Find all .tar.xz theme files
  find:
    paths: "{ playbook_dir }/cloudify-os-main/themes"
    patterns: "*.tar.xz"
  register: theme_archives

- name: Ensure /usr/share/themes exists inside chroot
  file:
    path: "{{ chroot_dir }}/usr/share/themes"
    state: directory
    mode: '0755'

- name: Extract all themes into chroot /usr/share/themes/
  unarchive:
    src: "{{ item.path }}"
    dest: "{{ chroot_dir }}/usr/share/themes/"
    remote_src: yes
  loop: "{{ theme_archives.files }}"

# === ICON THEMES ===

- name: Find all .tar.xz icon theme files
  find:
    paths: "{ playbook_dir }/cloudify-os-main/icons/"
    patterns: "*.tar.xz"
  register: icon_theme_archives

- name: Ensure /usr/share/icons exists inside chroot
  file:
    path: "{{ chroot_dir }}/usr/share/icons"
    state: directory
    mode: '0755'

- name: Extract all icon themes into chroot /usr/share/icons/
  unarchive:
    src: "{{ item.path }}"
    dest: "{{ chroot_dir }}/usr/share/icons/"
    remote_src: yes
  loop: "{{ icon_theme_archives.files }}"
