
- name: Fix ownership of ubuntu user config files
  file:
    path: "{{ chroot_dir }}/home/ubuntu/.config"
    owner: 1000
    group: 1000
    recurse: yes

- name: Copy default wallpaper into chroot for user-level usage
  copy:
    src: "{{ playbook_dir }}/cloudify-os-main/cloudify-wallpaper.png"
    dest: "{{ chroot_dir }}/usr/share/backgrounds/xfce/cloudify-wallpaper.png"
  become: true

# ==== Theme =====

- name: Create destination directory for WhiteSur theme
  ansible.builtin.file:
    path: "{{ chroot_dir }}/usr/share/themes/WhiteSur"
    state: directory
    mode: '0755'
    recurse: yes 

- name: Extract theme archive into chroot
  unarchive:
    src: "{{ playbook_dir }}/cloudify-os-main/themes/cloudi.tar.gz"
    dest: "{{ chroot_dir }}/usr/share/themes/WhiteSur"

# === ICON THEMES ===
- name: Create destination directory for WhiteSur theme
  ansible.builtin.file:
    path: "{{ chroot_dir }}/usr/share/icons/WhiteSur"
    state: directory
    mode: '0755'
    recurse: yes 

- name: Extract theme archive into chroot
  unarchive:
    src: "{{ playbook_dir }}/cloudify-os-main/icons/cloudi.tar.gz"
    dest: "{{ chroot_dir }}/usr/share/icons/WhiteSur"

- name: Create config directory
  ansible.builtin.file:
    path: "{{ chroot_dir }}/home/ubuntu/.config/xfce4/xfconf/xfce-perchannel-xml/"
    state: directory
    mode: '0755'
    recurse: yes 

## Desktop Settings ####
- name: Copy xsettings as default
  copy:
    src: "{{ playbook_dir }}/cloudify-os-main/config/xsettings.xml"
    dest: "{{ chroot_dir }}/home/ubuntu/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml"
    force: true 
  become: true

- name: Copy desktop settings as default
  copy:
    src: "{{ playbook_dir }}/cloudify-os-main/config/xfce4-desktop.xml"
    dest: "{{ chroot_dir }}/home/ubuntu/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml"
    force: true 
  become: true

## CONKY
- name: Install conky in chroot
  command: >
    chroot {{ chroot_dir }} apt-get install -y conky-all
  become: true

- name: Create Conky config directory for user
  file:
    path: "{{ chroot_dir }}/home/ubuntu/.config/conky"
    state: directory
    owner: 1000
    group: 1000
    mode: '0755'

- name: Copy custom Conky config
  copy:
    src: "{{ playbook_dir }}/cloudify-os-main/config/conky.conf"
    dest: "{{ chroot_dir }}/home/ubuntu/.config/conky/conky.conf"
    owner: 1000
    group: 1000
    mode: '0644'

- name: Create XFCE autostart directory
  file:
    path: "{{ chroot_dir }}/home/ubuntu/.config/autostart"
    state: directory
    owner: 1000
    group: 1000
    mode: '0755'

- name: Copy Conky autostart desktop entry
  copy:
    content: |
      [Desktop Entry]
      Type=Application
      Exec=conky -p 5
      Hidden=false
      NoDisplay=false
      X-GNOME-Autostart-enabled=true
      Name=Conky
      Comment=Start Conky system monitor
    dest: "{{ chroot_dir }}/home/ubuntu/.config/autostart/conky.desktop"
    owner: 1000
    group: 1000
    mode: '0644'
