- name: Ensure git is installed inside chroot
  command: chroot {{ chroot_dir }} apt-get install -y git
  become: true
- name: Clone Qogir GTK theme into chroot
  git:
    repo: "https://github.com/vinceliuice/Qogir-theme.git"
    dest: "{{ chroot_dir }}/opt/Qogir-theme"
    version: master

- name: Make install script executable
  file:
    path: "{{ chroot_dir }}/opt/Qogir-theme/install.sh"
    mode: '0755'

- name: Ensure XFCE per-channel XML config path exists
  file:
    path: "{{ chroot_dir }}/home/ubuntu/.config/xfce4/xfconf/xfce-perchannel-xml"
    state: directory
    owner: 1000
    group: 1000
    mode: '0755'
    recurse: yes
    
- name: Run Qogir GTK theme installer inside chroot
  command: >
    chroot {{ chroot_dir }} bash -c "cd /opt/Qogir-theme && ./install.sh -d /usr/share/themes"
  register: qogir_install
  failed_when: qogir_install.rc != 0 and 'already exists' not in qogir_install.stdout
  changed_when: "'Installing Qogir' in qogir_install.stdout"

- name: Set Qogir as default GTK and window manager theme
  block:
    - name: Set GTK theme
      copy:
        dest: "{{ chroot_dir }}/home/ubuntu/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml"
        content: |
          <?xml version="1.0" encoding="UTF-8"?>
          <channel name="xsettings" version="1.0">
            <property name="Net" type="empty">
              <property name="ThemeName" type="string" value="Qogir-dark"/>
            </property>
          </channel>
    - name: Set window manager theme (xfwm)
      copy:
        dest: "{{ chroot_dir }}/home/ubuntu/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml"
        content: |
          <?xml version="1.0" encoding="UTF-8"?>
          <channel name="xfwm4" version="1.0">
            <property name="general" type="empty">
              <property name="theme" type="string" value="Qogir-dark"/>
            </property>
          </channel>

- name: Fix ownership of ubuntu user config files
  file:
    path: "{{ chroot_dir }}/home/ubuntu/.config"
    owner: 1000
    group: 1000
    recurse: yes


- name: Copy default wallpaper into chroot
  copy:
    src: "{{ lookup('env', 'PWD') }}/cloudify-os-main/cloudify-wallpaper.png"
    dest: "{{ chroot_dir }}/usr/share/xfce4/backdrops/cloudify-wallpaper.png"
  become: true

- name: Set default XFCE background for ubuntu user
  copy:
    dest: "{{ chroot_dir }}/etc/xdg/xdg-xubuntu/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml"
    content: |
      <?xml version="1.0" encoding="UTF-8"?>

      <channel name="xfce4-desktop" version="1.0">
        <property name="backdrop">
          <property name="screen0">
            <property name="monitor0">
              <property name="image-path" type="string" value="/usr/share/backgrounds/xfce/cloudify-wallpaper.png"/>
            </property>
          </property>
        </property>
      </channel>
  become: true

- name: Set ownership of XFCE config
  file:
    path: "{{ chroot_dir }}/home/ubuntu/.config"
    owner: 1000
    group: 1000
    recurse: yes
